package com.xihuanicode.tlatoa.enums;

public enum GeneralizedScreenSize {	
	SCREENLAYOUT_SIZE_SMALL,
	SCREENLAYOUT_SIZE_NORMAL,
	SCREENLAYOUT_SIZE_LARGE,
	SCREENLAYOUT_SIZE_XLARGE,
	SCREENLAYOUT_SIZE_UNDEFINED
}